### ISSUE TITLE
feat: Add apy to selectSUmmaryData selector for labs

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-finance-v3#531]
**Elevator Pitch**
Add APY for the vaults holdings section

**Customer Value**
Right now, this is the returned data for selectSummaryData selector for labs:

return {
    totalDeposits: totalDeposited.toString(),
    totalEarnings: '0',
    estYearlyYeild: '0',
  };

But we need to add apy per request of the design team as:

The holdings value is the totalDeposits, so we are only missing the APY value in the selector.

**Definition of Done**
the APY is displayed through code
![image](https://user-images.githubusercontent.com/79029523/157988089-63cca829-6f26-4b3f-b376-a248f9724470.png)

**Design Approach**
Approach and considerations to build the task list / Existing code patterns in production code base that you will base your work off of.

**Additional Context**
Screenshots, UI/UX designs, links or other that will help implementing the feature.

**Comment by karelianpie** [comment]
Started looking into this one, created a draft PR https://github.com/yearn/yearn-finance-v3/pull/562

Wondering how is this APY calculated? Suppose you have 3 deposites, what would the APY be? I'm imagining that we would need to weigh each deposit/apy and then get the weighted average apy?

**Comment by xgambitox** [comment]
This issue was not clear enough. In these context `APY` represents the `Estimated Yearly Yield` for the connected wallet. In the home screen, for vaults, this value is fetched from the SDK, which aggregates this data from subgraph. To replicate this for Labs, its more of a manual task, trying to emulate what the subgraph does, since subgraph does not aggregate data for this special vaults (only yvBoost).

To obtain the `estimated yearly yield`, we need to calculate the `estimated earnings` for each vault a user has holdings (calculated using current APY), then `sum of all estimated earnings in Labs` / `sum of holdings in Labs`
