### ISSUE TITLE
MetaMask detection fails in Firefox

### ISSUE THREAD

**Issue by Jeiwan** [yearn/yearn-finance-v3#738]
**Describe the bug**
When connecting to MetaMask, the app fails to detect that MetaMask is installed. This has started recently.

**To Reproduce**
1. In Firefox, go to [https://yearn.finance](https://yearn.finance)
2. Click 'Connect Wallet'
3. Choose MetaMask
4. See "You'll need to install MetaMask to continue" message.

**Expected behavior**
The app detects MetaMask and connects to it.

**Screenshots**
In the JS console, I see this:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:1:144047
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:136:52
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:2132:49
```
Seems that CSP settings don't allow Firefox to initialize the MetaMask extension.

**Environment Information**
 - Browser: Firefox 103.0a1 (2022-06-15) (64-bit)

**Comment by xgambitox** [comment]
@Jeiwan thanks for detailed issue. 

We recently hardened our web app security and added the `script-src` to the CSP header. We now disallow inline scripts from being injected into our site. Metamask extension injects the web3 provider on `window.ethereum` this way, but seems like it violates this CSP on Firefox since they apply it more strictly, and also is an issue for the Metamask mobile app. Metamask has knowledge of this issue but has not being solved yet https://github.com/MetaMask/metamask-extension/issues/3133.

Since we dont want to downgrade our security (unless its much needed), we will need to find a workaround until it is solved by Metamask.

**Comment by Jeiwan** [comment]
@xgambitox I see, thanks for clarifying.

So the only workaround is to use a different browser or disable CSP in Firefox (which is unsafe). I'll close the issue since this is an upstream issue.

**Comment by xgambitox** [comment]
Was able to get a custom workaround working [here](https://github.com/yearn/yearn-finance-v3/pull/739). Will do some QA and release to prod.
